package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildSteps.ScriptBuildStep
import jetbrains.buildServer.configs.kotlin.buildSteps.script
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'SubProject1_TestSomeCommands'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("SubProject1_TestSomeCommands")) {
    expectSteps {
        script {
            name = "Create Text File"
            id = "Create_Text_File"
            workingDir = "/"
            scriptContent = "touch self_created_file.txt"
        }
        script {
            name = "Create Second File"
            id = "Create_Second_File"
            workingDir = "/"
            scriptContent = """echo "Test Note for Second reated file %env.TestParam_1%" >  second_created_file_%env.TestParam_1%.txt"""
        }
    }
    steps {
        update<ScriptBuildStep>(1) {
            clearConditions()
            scriptContent = """
                echo ${TQ}Test Note for Second reated file %env.TestParam_1% and try get new feature:
                     - branch name IS: %teamcity.build.branch%
                     Last string for tests$TQ >  second_created_file_%env.TestParam_1%.txt
            """.trimIndent()
        }
    }
}
